[package]
name = 'settings-schema-derive'
version = '0.1.0'
authors = ['Riccardo Zaglia <riccardo.zaglia5@gmail.com>']
license = 'MIT'
edition = '2018'

[lib]
proc-macro = true

[dependencies]
proc-macro2 = '^1.0'
syn = '^1.0'
quote = '^1.0'